// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID       int64  `gorm:"column:user_id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"user_id"`
	UserNickname string `gorm:"column:user_nickname;type:varchar(50);not null" json:"user_nickname"`
	UserHeader   string `gorm:"column:user_header;type:varchar(200);not null" json:"user_header"`
	UserSex      int32  `gorm:"column:user_sex;type:tinyint unsigned;not null" json:"user_sex"`      // 性别，1男2女
	PhoneCountry string `gorm:"column:phone_country;type:varchar(30);not null" json:"phone_country"` // 手机号国家代码
	UserPhone    string `gorm:"column:user_phone;type:varchar(30);not null" json:"user_phone"`       // 手机号码
	State        int32  `gorm:"column:state;type:tinyint unsigned;not null;default:1" json:"state"`  // 状态，1正常，0禁用，2注销
	UserBirth    int32  `gorm:"column:user_birth;type:int;not null" json:"user_birth"`               // 生日
	IsRobot      int32  `gorm:"column:is_robot;type:tinyint unsigned;not null" json:"is_robot"`      // 0真人，1马甲
	UserLocation string `gorm:"column:user_location;type:varchar(60);not null" json:"user_location"` // 用户位置
	UserLngLat   string `gorm:"column:user_lng_lat;type:geometry" json:"user_lng_lat"`               // 用户坐标
	UserGeohash  string `gorm:"column:user_geohash;type:varchar(60)" json:"user_geohash"`            // 经纬度geohash值
	CreateTime   int32  `gorm:"column:create_time;type:int unsigned;not null" json:"create_time"`
	UpdateTime   int32  `gorm:"column:update_time;type:int unsigned;not null" json:"update_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
